### ISSUE TITLE
issue basic 

### ISSUE THREAD

**Issue by giter404** [jameszah/ESP32-CAM-Video-Recorder-junior#19]
hi sir , 
i downloaded zip of your code ,and opened v58 folder , then opened 'ESP32-CAM-Video-Recorder-junior-58x.ino'.
then while uploading code error showed . 
please help

**Comment by jameszah** [comment]
I need a bit more information - like the arduino errors

**Comment by jameszah** [comment]
https://github.com/jameszah/ESP32-CAM-Video-Recorder-junior/blob/b1169bb7aea5afb721b0807aad8bf33840660215/v58/ESP32-CAM-Video-Recorder-junior-58x.ino#L52

![image](https://user-images.githubusercontent.com/36938190/177698411-1e1b29bd-6586-46c3-9bed-c957e7049536.png)

**Comment by giter404** [comment]
yo , it works now , thanks man i appreciate that .👍😊

**Comment by giter404** [comment]
thanks man it works now 👍😊

**Comment by esalefu** [comment]
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Jul 7, 2022, 17:04 by ***@***.***:

>
>
>
>
> thanks man it works now 👍😊
>
>





hi  what program work?
