### ISSUE TITLE
What‘s the major difference between these two project?

### ISSUE THREAD

**Issue by duchengyao** [jameszah/ESP32-CAM-Video-Recorder-junior#32]
Thanks for sharing this project.

Because English is not my mother tongue, it is difficult to read a long readme.

Can you briefly outline the biggest differences between the two programs?
What was streamlined for this project.

simple version: https://github.com/jameszah/ESP32-CAM-Video-Recorder-junior

full version: https://github.com/jameszah/ESP32-CAM-Video-Recorder

Thanks ^_^

**Comment by jameszah** [comment]
"junior" is newer, simpler, quicker, plus fully configurable after installing a generic version from https://jameszah.github.io/ESP32-CAM-VideoCam/

"original" has a some old inefficient code, but it does have the feature of sending the first frame of a video to telegram.org and your phone to give you some notice of the video being recorded.

Simple recording, or a starting place to make your own project, use "junior".

**Comment by duchengyao** [comment]
This project has been successfully used, thank you for your help!
