### ISSUE TITLE
deal with offline logging project

### ISSUE THREAD

**Issue by nices0325** [jameszah/ESP32-CAM-Video-Recorder-junior#7]
First of all, Do appreciate for the awesome library!!
I'm doing my own project using this library. Due to I'm not a programmer, but newbie for the coding, It's a little bit hard for me to understand the codes you wrote..
Is it essential to use wifi to use activate the esp32 cam? I'm afraid to modify the codes, due to sudden inactivation of the esp32 cam... How can I just use this library only for offline sd card logging.. Can you get me a little tip for me?
thanks again for your library

**Comment by jameszah** [comment]
You can just use that version 10x from Sep 2020.  It has no internet, so just compile and download, and you should be recording.  

Make sure you have arduino board esp32 version 1.04.   Version 1.05 arrived a few days ago, and the code needs a few mods to make it work.

New version with 1.05 support, plus the timelapse, and file deleting coming shortly.

![image](https://user-images.githubusercontent.com/36938190/109408991-0ac39f80-794c-11eb-965e-6be0cffc5719.png)
