### ISSUE TITLE
ESP32 CAM colour control

### ISSUE THREAD

**Issue by JohnWeid** [jameszah/ESP32-CAM-Video-Recorder-junior#9]
Hi Jameszah, Great work. The "junior" has been just what I've been after...just a simple Video recording to an SD card..great stuff..many thanks.
I'm not a programmer, just a follower/user (wish I could program like you guys !!)...However whist "junior" is doing what I am after, I've been having problems getting any reasonable color in my video results.
I'm sure that it's just me but at this stage my results are just grey with some blue. I've tried going back to VX10 to see if simplicity might have been the answer but the answer is no.
Can you advise where I might be able to update the settings to improve my color results please.
Many thanks again for your great work.
John Weid
![Snapshot 1 (12-Jun-21 10-05 AM)](https://user-images.githubusercontent.com/85771418/121759257-24d66600-cb68-11eb-98dc-1f6240fb7086.png)

**Comment by jameszah** [comment]
https://upload.wikimedia.org/wikipedia/commons/9/9a/Sensor_sizes_overlaid_inside_-_updated.svg

That is the cost of a $1 sensor with a $1 lens and a 1/4 inch sensor. 😄 

The auto-brigtness auto-contrast etc is mixing the bright sky with the dark ground and splitting the difference.  You could try tilting the camera up so you just get the sky clouds and tree-tops and it might work.  Or cut out the sky and just look at the ground.
